### ISSUE TITLE
All scores are (0,0)

### ISSUE THREAD

**Issue by ayushidalmia** [kevincobain2000/sentiment_classifier#1]
Hi,

I have used senti_classifier before and it worked fine. However, I had reinstalled it and since then it is giving zero score for anything and everything. Can anyone please help?

**Comment by ayushidalmia** [comment]
Attaching image

/home/ayushi/Pictures/Screenshot from 2015-01-21 20:57:31.png

**Comment by ayushidalmia** [comment]
Attaching image here: 

![screenshot from 2015-01-21 20 57 31](https://cloud.githubusercontent.com/assets/5400513/5838950/e5fed544-a1b0-11e4-8ed4-07550ff25211.png)

**Comment by ayushidalmia** [comment]
Attaching screenshot from here:

![screenshot from 2015-01-21 20 57 31](https://cloud.githubusercontent.com/assets/5400513/5838967/f8e27d64-a1b0-11e4-81ba-89fa21a8b1d1.png)

**Comment by kevincobain2000** [comment]
Seems to me that it is not able to read the pickle of sentiwordnet. Thanks, will do over the weekend. 
Anyways this library has some performance issues, so I have been thinking about rewriting much wiser on ruby and pack it into gem

**Comment by cyri113** [comment]
Have you had a chance to look at what is causing this? Thanks!

**Comment by kevincobain2000** [comment]
Hi @ayushidalmia @cderche 
Sorry guys, I had been busy. Its a dirty fix but for now the scores will cooperate !
Somehow I am not able to pickle the sentiwordnet like I was able to before. I have created a new issue for that and, will fix it (https://github.com/kevincobain2000/sentiment_classifier/blob/cf725507df33c733914e91ddd933b7f326020068/src/senti_classifier/senti_classifier.py#L220-L224) soon to boost up the performance. https://github.com/kevincobain2000/sentiment_classifier/issues/2

```
runs the code     print classify( ["The movie was the worst movie"], synsets_scores, bag_of_words)
03/31/15 @ 9:40PM - kevincobain2000@Mac Air 

~/Downloads/sentiment_classifier/src/senti_classifier@master* python senti_classifier.py -p data/SentiWordNet_3.0.0_20130122.txt
(0, 0.875)
```

PS: Although I have pushed the latest version of SentiWordNet https://github.com/kevincobain2000/sentiment_classifier/commit/8a44b86b9a1cb68f5151c28b39c3135cb0aaca3d, you can download it yourself too

**Comment by kevincobain2000** [comment]
@ayushidalmia #1 and #2 Fixed ! https://github.com/kevincobain2000/sentiment_classifier/commit/13c6ac47d07a9808d06ec8fe6924d03f5246d001#diff-a7113eea41266357d694a46205cd66e2R187
- Download the zip from github
- reinstall it

```
03/31/15 @11:21PM - kevincobain2000@Mac Air ~/Downloads/sentiment_classifier@master* sudo python setup.py install
...
...
Using /Library/Python/2.7/site-packages
Finished processing dependencies for sentiment-classifier==0.5

03/31/15 @11:21PM - kevincobain2000@Mac Air ~/Downloads/sentiment_classifier@master* python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from senti_classifier import senti_classifier
>>> sentences = ['The movie was the worst movie', 'It was the worst acting by the actors']
>>> pos_score, neg_score = senti_classifier.polarity_scores(sentences)
>>> print pos_score, neg_score
0.0 1.7
```

**Comment by ayushidalmia** [comment]
Cool! Will try it out in sometime.

**Comment by prasadpande1990** [comment]
I pull the latest files from this branch but still getting 0,0 values for pos_score and neg_score

**Comment by prasadpande1990** [comment]
Attaching the code and output for reference:

Code:
pos_score, neg_score = senti_classifier.polarity_scores('The movie was the worst movie')
print("Positive Score")
print(pos_score)
print("Negative Score")
print(neg_score)

Output:
C:\Python27\python.exe C:/Users/Sunil/PycharmProjects/OpinionMining/JSONParsing.py
Positive Score
0.0
Negative Score
0.0
![capture_senti](https://cloud.githubusercontent.com/assets/8678175/7334078/dddc99f6-eb4c-11e4-8119-135e5ee3b934.JPG)

**Comment by prasadpande1990** [comment]
@ayushidalmia  Can you confirm if it is working?

**Comment by nishant2295** [comment]
How do i train the classifier with my reviews??
Can anyone help me with this?
